from __future__ import annotations

import csv
import json
from datetime import UTC, datetime
from pathlib import Path

from .models import AppResult


def entry_to_markdown(app: AppResult) -> str:
    line = f"* [{app.name}]({app.urls[0]})"
    if app.desc:
        line += f" - {app.desc}"
    extra: list[str] = []
    if app.confidence:
        extra.append(f"confidence: {app.confidence}")
    if app.usefulness:
        extra.append(f"usefulness: {app.usefulness}")
    if app.release_info.release_url:
        extra.append(f"[release]({app.release_info.release_url})")
    if extra:
        line += " (" + ", ".join(extra) + ")"
    return line


def section_to_markdown(title: str, apps: list[AppResult], recent_days: int) -> str:
    report = "\n"
    now = datetime.now(UTC)
    recent: list[AppResult] = []
    stale: list[AppResult] = []

    for app in apps:
        if app.last_updated and (now - app.last_updated).days <= recent_days:
            recent.append(app)
        else:
            stale.append(app)

    if recent or stale:
        report += f"### {title}\n\n"

    if recent:
        report += f"#### Updated in the last {recent_days} days\n\n"
        for app in recent:
            report += entry_to_markdown(app) + "\n"

    if stale:
        report += f"\n#### Older or unknown update date\n\n"
        for app in stale:
            report += entry_to_markdown(app) + "\n"

    return report


def write_summary(path: Path, apps: list[AppResult], recent_days: int) -> None:
    report = (
        "## Scan results\n"
        "> [!IMPORTANT]\n"
        "> This file is automatically generated. Do not edit.\n\n"
        "This document tracks repos and apps that appear to use Shizuku in some way but are not yet listed in the known reference files.\n\n"
        "Entries are sorted by name and grouped by release availability.\n\n"
    )
    with_releases = [a for a in apps if a.has_downloads or a.release_info.has_downloads]
    without_releases = [a for a in apps if not (a.has_downloads or a.release_info.has_downloads)]
    report += section_to_markdown("Apps with releases", with_releases, recent_days)
    report += section_to_markdown("Apps with no releases", without_releases, recent_days)
    path.write_text(report, encoding="utf-8")


def write_json(path: Path, apps: list[AppResult]) -> None:
    path.write_text(
        json.dumps([app.to_dict() for app in apps], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def write_csv(path: Path, apps: list[AppResult]) -> None:
    fieldnames = [
        "name",
        "primary_url",
        "scanner",
        "desc",
        "package_id",
        "application_id",
        "last_updated",
        "has_downloads",
        "confidence",
        "usefulness",
        "release_url",
        "release_tag",
    ]
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for app in apps:
            writer.writerow(
                {
                    "name": app.name,
                    "primary_url": app.urls[0] if app.urls else "",
                    "scanner": app.scanner,
                    "desc": app.desc or "",
                    "package_id": app.package_id or "",
                    "application_id": app.application_id or "",
                    "last_updated": app.last_updated.isoformat() if app.last_updated else "",
                    "has_downloads": app.has_downloads or app.release_info.has_downloads,
                    "confidence": app.confidence,
                    "usefulness": app.usefulness,
                    "release_url": app.release_info.release_url or "",
                    "release_tag": app.release_info.release_tag or "",
                }
            )


def write_html(path: Path, apps: list[AppResult]) -> None:
    rows = []
    for app in apps:
        primary_url = app.urls[0] if app.urls else ""
        release = app.release_info.release_url or ""
        rows.append(
            "<tr>"
            f"<td><a href='{primary_url}'>{app.name}</a></td>"
            f"<td>{app.confidence}</td>"
            f"<td>{app.usefulness}</td>"
            f"<td>{'yes' if (app.has_downloads or app.release_info.has_downloads) else 'no'}</td>"
            f"<td>{app.release_info.release_tag or ''}</td>"
            f"<td><a href='{release}'>release</a></td>" if release else "<td></td>"
            "</tr>"
        )
    html = f"""<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <title>App crawler report</title>
  <style>
    body {{ font-family: sans-serif; margin: 2rem; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 0.5rem; text-align: left; }}
    th {{ background: #f5f5f5; }}
  </style>
</head>
<body>
  <h1>App crawler report</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Confidence</th>
        <th>Usefulness</th>
        <th>Downloads</th>
        <th>Release tag</th>
        <th>Release</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows)}
    </tbody>
  </table>
</body>
</html>
"""
    path.write_text(html, encoding="utf-8")


def write_stats(path: Path, apps: list[AppResult]) -> None:
    stats = {
        "total": len(apps),
        "with_downloads": sum(1 for a in apps if a.has_downloads or a.release_info.has_downloads),
        "confidence": {
            level: sum(1 for a in apps if a.confidence == level)
            for level in ("high", "medium", "low")
        },
        "usefulness": {
            level: sum(1 for a in apps if a.usefulness == level)
            for level in ("high", "medium", "low")
        },
    }
    path.write_text(json.dumps(stats, indent=2), encoding="utf-8")


def write_diff(path: Path, current_apps: list[AppResult], previous_apps: list[AppResult]) -> None:
    current_keys = {app.identity_key(): app for app in current_apps}
    previous_keys = {app.identity_key(): app for app in previous_apps}

    added = [app.to_dict() for key, app in current_keys.items() if key not in previous_keys]
    removed = [app.to_dict() for key, app in previous_keys.items() if key not in current_keys]

    diff = {
        "added": added,
        "removed": removed,
    }
    path.write_text(json.dumps(diff, indent=2, ensure_ascii=False), encoding="utf-8")
