from __future__ import annotations

import csv
import html
import json
from datetime import UTC, datetime
from pathlib import Path

from .models import AppResult


def entry_to_markdown(app: AppResult) -> str:
    line = f"* [{app.name}]({app.urls[0]})"
    if app.desc:
        line += f" - {app.desc}"
    extra: list[str] = []
    extra.append(f"confidence: {app.confidence}")
    extra.append(f"usefulness: {app.usefulness}")
    extra.append(f"status: {app.status}")
    if app.release_info.release_url:
        extra.append(f"[release]({app.release_info.release_url})")
    if app.release_info.quality_label and app.release_info.quality_label != 'unknown':
        extra.append(f"artifact-quality: {app.release_info.quality_label}")
    if app.evidence:
        ev = app.evidence[0]
        snippet = ev.detail or ev.reason
        extra.append(f"evidence: {snippet[:80]}".replace("\n", " "))
    line += " (" + ", ".join(extra) + ")"
    return line


def section_to_markdown(title: str, apps: list[AppResult], recent_days: int) -> str:
    report = "\n"
    now = datetime.now(UTC)
    recent: list[AppResult] = []
    stale: list[AppResult] = []

    for app in apps:
        if app.last_updated and (now - app.last_updated).days <= recent_days:
            recent.append(app)
        else:
            stale.append(app)

    if recent or stale:
        report += f"### {title}\n\n"

    if recent:
        report += f"#### Updated in the last {recent_days} days\n\n"
        for app in recent:
            report += entry_to_markdown(app) + "\n"

    if stale:
        report += f"\n#### Older or unknown update date\n\n"
        for app in stale:
            report += entry_to_markdown(app) + "\n"

    return report


def write_summary(path: Path, apps: list[AppResult], recent_days: int) -> None:
    report = (
        "## Scan results\n"
        "> [!IMPORTANT]\n"
        "> This file is automatically generated. Do not edit.\n\n"
        "This document tracks repos and apps that appear to use Shizuku in some way but are not yet listed in the known reference files.\n\n"
        "Entries are sorted by name and grouped by release availability.\n\n"
    )
    with_releases = [a for a in apps if a.has_downloads or a.release_info.has_downloads]
    without_releases = [a for a in apps if not (a.has_downloads or a.release_info.has_downloads)]
    report += section_to_markdown("Apps with releases", with_releases, recent_days)
    report += section_to_markdown("Apps with no releases", without_releases, recent_days)
    path.write_text(report, encoding="utf-8")


def write_json(path: Path, apps: list[AppResult]) -> None:
    path.write_text(
        json.dumps([app.to_dict() for app in apps], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def write_csv(path: Path, apps: list[AppResult]) -> None:
    fieldnames = [
        "name",
        "primary_url",
        "scanner",
        "desc",
        "package_id",
        "application_id",
        "last_updated",
        "has_downloads",
        "confidence",
        "usefulness",
        "status",
        "release_url",
        "release_tag",
        "artifact_quality",
        "apk_assets",
        "aab_assets",
        "universal_apk_assets",
        "split_apk_assets",
        "checksum_assets",
        "evidence",
    ]
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for app in apps:
            writer.writerow(
                {
                    "name": app.name,
                    "primary_url": app.urls[0] if app.urls else "",
                    "scanner": app.scanner,
                    "desc": app.desc or "",
                    "package_id": app.package_id or "",
                    "application_id": app.application_id or "",
                    "last_updated": app.last_updated.isoformat() if app.last_updated else "",
                    "has_downloads": app.has_downloads or app.release_info.has_downloads,
                    "confidence": app.confidence,
                    "usefulness": app.usefulness,
                    "status": app.status,
                    "release_url": app.release_info.release_url or "",
                    "release_tag": app.release_info.release_tag or "",
                    "artifact_quality": app.release_info.quality_label,
                    "apk_assets": ", ".join(app.release_info.apk_assets),
                    "aab_assets": ", ".join(app.release_info.aab_assets),
                    "universal_apk_assets": ", ".join(app.release_info.universal_apk_assets),
                    "split_apk_assets": ", ".join(app.release_info.split_apk_assets),
                    "checksum_assets": ", ".join(app.release_info.checksum_assets),
                    "evidence": (app.evidence[0].detail or app.evidence[0].reason) if app.evidence else "",
                }
            )


def write_html(path: Path, apps: list[AppResult]) -> None:
    rows = []
    for app in apps:
        primary_url = app.urls[0] if app.urls else ""
        release = app.release_info.release_url or ""
        evidence = (app.evidence[0].detail or app.evidence[0].reason) if app.evidence else ""
        apk_assets = ", ".join(app.release_info.apk_assets)
        quality = app.release_info.quality_label
        rows.append(
            "<tr "
            f"data-name='{html.escape(app.name.lower())}' "
            f"data-confidence='{html.escape(app.confidence)}' "
            f"data-usefulness='{html.escape(app.usefulness)}' "
            f"data-status='{html.escape(app.status)}'>"
            f"<td><a href='{html.escape(primary_url)}'>{html.escape(app.name)}</a></td>"
            f"<td>{html.escape(app.scanner)}</td>"
            f"<td>{html.escape(app.confidence)}</td>"
            f"<td>{html.escape(app.usefulness)}</td>"
            f"<td>{html.escape(app.status)}</td>"
            f"<td>{'yes' if (app.has_downloads or app.release_info.has_downloads) else 'no'}</td>"
            f"<td>{html.escape(app.release_info.release_tag or '')}</td>"
            f"<td>{html.escape(quality)}</td>"
            f"<td>{html.escape(apk_assets)}</td>"
            f"<td>{html.escape(evidence[:120])}</td>"
            + (f"<td><a href='{html.escape(release)}'>release</a></td>" if release else "<td></td>")
            + "</tr>"
        )
    html_doc = f"""<!doctype html>
<html>
<head>
  <meta charset='utf-8'>
  <title>App crawler report</title>
  <style>
    body {{ font-family: sans-serif; margin: 2rem; }}
    .controls {{ display: flex; gap: 0.75rem; flex-wrap: wrap; margin-bottom: 1rem; }}
    input, select {{ padding: 0.5rem; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 0.5rem; text-align: left; vertical-align: top; }}
    th {{ background: #f5f5f5; position: sticky; top: 0; }}
    .muted {{ color: #666; margin-bottom: 1rem; }}
  </style>
</head>
<body>
  <h1>App crawler report</h1>
  <p class='muted'>Search and filter results by confidence, usefulness, and review status.</p>
  <div class='controls'>
    <input id='search' placeholder='Search name...'>
    <select id='confidence'>
      <option value=''>All confidence</option>
      <option value='high'>high</option>
      <option value='medium'>medium</option>
      <option value='low'>low</option>
    </select>
    <select id='usefulness'>
      <option value=''>All usefulness</option>
      <option value='high'>high</option>
      <option value='medium'>medium</option>
      <option value='low'>low</option>
    </select>
    <select id='status'>
      <option value=''>All status</option>
      <option value='new'>new</option>
      <option value='confirmed'>confirmed</option>
      <option value='reviewed'>reviewed</option>
      <option value='false_positive'>false_positive</option>
      <option value='archived'>archived</option>
    </select>
  </div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Scanner</th>
        <th>Confidence</th>
        <th>Usefulness</th>
        <th>Status</th>
        <th>Downloads</th>
        <th>Release tag</th>
        <th>Artifact quality</th>
        <th>APK assets</th>
        <th>Evidence</th>
        <th>Release</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows)}
    </tbody>
  </table>
  <script>
    const search = document.getElementById('search');
    const confidence = document.getElementById('confidence');
    const usefulness = document.getElementById('usefulness');
    const status = document.getElementById('status');
    const rows = Array.from(document.querySelectorAll('tbody tr'));

    function applyFilters() {{
      const q = search.value.trim().toLowerCase();
      const c = confidence.value;
      const u = usefulness.value;
      const s = status.value;
      rows.forEach((row) => {{
        const okQ = !q || row.dataset.name.includes(q);
        const okC = !c || row.dataset.confidence === c;
        const okU = !u || row.dataset.usefulness === u;
        const okS = !s || row.dataset.status === s;
        row.style.display = okQ && okC && okU && okS ? '' : 'none';
      }});
    }}

    [search, confidence, usefulness, status].forEach(el => el.addEventListener('input', applyFilters));
    [confidence, usefulness, status].forEach(el => el.addEventListener('change', applyFilters));
  </script>
</body>
</html>
"""
    path.write_text(html_doc, encoding="utf-8")


def write_stats(path: Path, apps: list[AppResult]) -> None:
    stats = {
        "total": len(apps),
        "with_downloads": sum(1 for a in apps if a.has_downloads or a.release_info.has_downloads),
        "with_apk_assets": sum(1 for a in apps if a.release_info.apk_assets),
        "with_checksum_assets": sum(1 for a in apps if a.release_info.checksum_assets),
        "quality_labels": {
            label: sum(1 for a in apps if a.release_info.quality_label == label)
            for label in sorted({a.release_info.quality_label for a in apps} | {'none'})
        },
        "scanner_counts": {
            scanner: sum(1 for a in apps if a.scanner == scanner)
            for scanner in sorted({a.scanner for a in apps})
        },
        "confidence": {
            level: sum(1 for a in apps if a.confidence == level)
            for level in ("high", "medium", "low")
        },
        "usefulness": {
            level: sum(1 for a in apps if a.usefulness == level)
            for level in ("high", "medium", "low")
        },
        "statuses": {
            status: sum(1 for a in apps if a.status == status)
            for status in sorted({a.status for a in apps} | {"new"})
        },
    }
    path.write_text(json.dumps(stats, indent=2), encoding="utf-8")


def write_diff(path: Path, current_apps: list[AppResult], previous_apps: list[AppResult]) -> None:
    current_keys = {app.identity_key(): app for app in current_apps}
    previous_keys = {app.identity_key(): app for app in previous_apps}

    added = [app.to_dict() for key, app in current_keys.items() if key not in previous_keys]
    removed = [app.to_dict() for key, app in previous_keys.items() if key not in current_keys]

    diff = {
        "added": added,
        "removed": removed,
    }
    path.write_text(json.dumps(diff, indent=2, ensure_ascii=False), encoding="utf-8")
